export function ComoFunciona() {
  return (
    <section id="como" style={{ position: 'relative', padding: 'clamp(64px,9vw,120px) clamp(20px,4vw,48px)', background: 'linear-gradient(180deg,#0d0b1a,#08070f)', borderTop: '1px solid rgba(255,255,255,0.05)' }}>
      <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
        <p style={{ margin: '0 0 14px', fontFamily: "'JetBrains Mono', monospace", fontSize: '13px', letterSpacing: '0.18em', textTransform: 'uppercase', color: '#7d9bff' }}>Como funciona</p>
        <h2 style={{ margin: '0 0 48px', fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,46px)', lineHeight: '1.1', letterSpacing: '-0.02em', color: '#f2f1f8' }}>Do requisito ao pull request em cinco passos</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', padding: '24px 0', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><span style={{ flexShrink: 0, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,40px)', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent', minWidth: '64px' }}>01</span><div style={{ paddingTop: '4px' }}><h3 style={{ margin: '0 0 6px', fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 'clamp(18px,2.2vw,22px)', color: '#f2f1f8' }}>Conecte seu projeto e repositório</h3><p style={{ margin: 0, fontSize: '15.5px', lineHeight: '1.55', color: '#a09db5' }}>Integre o AgentOps ao seu código e ao GitHub.</p></div></div>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', padding: '24px 0', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><span style={{ flexShrink: 0, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,40px)', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent', minWidth: '64px' }}>02</span><div style={{ paddingTop: '4px' }}><h3 style={{ margin: '0 0 6px', fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 'clamp(18px,2.2vw,22px)', color: '#f2f1f8' }}>Registre ou importe uma demanda</h3><p style={{ margin: 0, fontSize: '15.5px', lineHeight: '1.55', color: '#a09db5' }}>Um work item, uma issue ou um requisito técnico.</p></div></div>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', padding: '24px 0', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><span style={{ flexShrink: 0, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,40px)', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent', minWidth: '64px' }}>03</span><div style={{ paddingTop: '4px' }}><h3 style={{ margin: '0 0 6px', fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 'clamp(18px,2.2vw,22px)', color: '#f2f1f8' }}>Os agentes analisam, planejam e implementam</h3><p style={{ margin: 0, fontSize: '15.5px', lineHeight: '1.55', color: '#a09db5' }}>O fluxo roda por fases, com cada agente no seu papel.</p></div></div>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', padding: '24px 0', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><span style={{ flexShrink: 0, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,40px)', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent', minWidth: '64px' }}>04</span><div style={{ paddingTop: '4px' }}><h3 style={{ margin: '0 0 6px', fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 'clamp(18px,2.2vw,22px)', color: '#f2f1f8' }}>O AgentOps gera logs, fases e rastreabilidade</h3><p style={{ margin: 0, fontSize: '15.5px', lineHeight: '1.55', color: '#a09db5' }}>Você acompanha cada passo com evidências.</p></div></div>
          <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start', padding: '24px 0', borderBottom: '1px solid rgba(255,255,255,0.07)' }}><span style={{ flexShrink: 0, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,40px)', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent', minWidth: '64px' }}>05</span><div style={{ paddingTop: '4px' }}><h3 style={{ margin: '0 0 6px', fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 'clamp(18px,2.2vw,22px)', color: '#f2f1f8' }}>Você revisa, aprova, homologa e evolui</h3><p style={{ margin: 0, fontSize: '15.5px', lineHeight: '1.55', color: '#a09db5' }}>Aprovação humana fecha o ciclo — ou pede retrabalho.</p></div></div>
        </div>
      </div>
    </section>
  );
}
