export function Recebe() {
  return (
    <section style={{ position: 'relative', padding: 'clamp(64px,9vw,120px) clamp(20px,4vw,48px)' }}>
      <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
        <p style={{ margin: '0 0 14px', fontFamily: "'JetBrains Mono',monospace", fontSize: '13px', letterSpacing: '0.18em', textTransform: 'uppercase', color: '#7d9bff' }}>A oferta</p>
        <h2 style={{ margin: '0 0 12px', fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 'clamp(28px,4vw,46px)', lineHeight: '1.1', letterSpacing: '-0.02em', color: '#f2f1f8' }}>O que você recebe</h2>
        <p style={{ margin: '0 0 40px', fontSize: '16px', color: '#a09db5', maxWidth: '60ch' }}>Acesso ao código-fonte de um produto real e em evolução — não a slides, não a um curso gravado.</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: '14px' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Código-fonte completo do AgentOps</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Front-end em Next.js 13 + PrimeReact</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Back-end em FastAPI (Python 3.12)</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Arquitetura modular e desacoplada</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Base de agentes especializados</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Estrutura de orquestração de execuções</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Modelagem de projetos, repositórios, work items e agent runs</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Documentação técnica inicial</span></div>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', padding: '18px 20px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', background: 'rgba(255,255,255,0.025)' }}><span style={{ flexShrink: 0, width: '24px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#5b8cff,#a06bff)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '13px' }}>✓</span><span style={{ fontSize: '15px', color: '#e2e1ee', lineHeight: '1.45' }}>Projeto em evolução para customizar, estudar, vender ou virar produto</span></div>
        </div>
      </div>
    </section>
  )
}
